In [2]:
import numpy as np

In [5]:
a=[5,6,7,8]
b=np.array(a,dtype=np.uint8)

print(b.shape,b.size)

(4,) 4


In [9]:
ma=np.random.rand(3,3)
mb=np.random.rand(3,3)
print(ma,'\n'+str(mb))

[[0.76559706 0.77544914 0.19332892]
 [0.56953236 0.99600208 0.50338037]
 [0.24816675 0.06610546 0.7087452 ]] 
[[0.38000508 0.69782849 0.30653304]
 [0.42331554 0.99605756 0.39980417]
 [0.15642758 0.9794008  0.4069855 ]]
